# Generated by Django 5.0.4 on 2024-05-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='isOccupied',
            field=models.BooleanField(default=False),
        ),
    ]
